version: "3.1"

services:
    nginx:
        image: nginx:alpine
        working_dir: /var/www/sre
        volumes:
            - ./:/var/www/sre
            - ./docker/hosts/app.conf:/etc/nginx/conf.d/default.conf
            - ./docker/hosts/app-defaults:/etc/nginx/app-defaults
        ports:
            - "86:80"
        links:
            - php
    php:
        build: docker/images/php
        working_dir: /var/www/sre
        volumes:
            - ./:/var/www/sre
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        links:
            - postgres
    postgres:
        image: postgres:alpine
        volumes:
            - ./docker/images/postgres/init-extensions.sh:/docker-entrypoint-initdb.d/init-extensions.sh
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
